name: 'publish'
on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    environment: 
      name: BUILD
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      #
      - name: install frontend dependencies
        run: yarn --frozen-lockfile && yarn install --network-timeout 600000 # change this to npm or pnpm depending on which one you use
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          

      - name: dispatch prepare
        run: |
          curl -sL $url | openssl sha256 | awk '{print $2}' > checksum.txt
          echo "sha=$(cat checksum.txt)" >> $GITHUB_ENV

      - name: dispatch to homebrew/formulae
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.HOMEBREW_REPO_GITHUB_TOKEN }}
          repository: sei-12/homebrew-formulae
          event-type: update
          client-payload: '{"version": "${{ env.version }}", "sha": "${{ env.sha }}"}'
